# Generated by Django 4.0.5 on 2023-05-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing', models.CharField(max_length=1000)),
                ('winner', models.BooleanField()),
                ('typeslist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeslist')),
            ],
        ),
    ]
