# Generated by Django 4.0.5 on 2023-06-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('isplus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LottoDraw',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LottoDraws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isplus', models.BooleanField()),
                ('betlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lottodraw')),
            ],
        ),
        migrations.RenameModel(
            old_name='TypesList',
            new_name='BetList',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='bet',
            name='typeslist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.betlist'),
        ),
    ]
