# Generated by Django 4.0.5 on 2023-06-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bet_lottodraw_lottodraws_typing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typing',
            name='betlist',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='main.lottodraw'),
        ),
    ]
