# Generated by Django 4.0.5 on 2023-07-19 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_remove_bet_typeslist_bet_name_bet_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bet',
            new_name='UserBet',
        ),
    ]
