# Generated by Django 4.0.5 on 2023-07-20 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_remove_number_bet_number_user_number_userbet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userbet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbet', to=settings.AUTH_USER_MODEL),
        ),
    ]
