# Generated by Django 4.0.5 on 2023-07-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_userbet_id_alter_userbet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='user',
        ),
    ]
